---
services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped

    environment:
      PUID: "1000"
      PGID: "100"
      TZ: "America/New_York"

    volumes:
      - /opt/docker/data/prowlarr:/config

    ports:
      - "9696:9696"

    logging:
      driver: local
